[cursor]
style = "Block"

[font]
size = 10.0

[font.normal]
family = "Liberation Mono"
style = "Regular"

[font.bold]
family = "Liberation Mono"
style = "Bold"

[font.italic]
family = "Liberation Mono"
style = "Italic"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1
blur = true

[window.padding]
x = 12
y = 12

[window.dimensions]
columns = 90
lines = 25

[colors.normal]
black =   '#282828'
red =     '#cc241d'
green =   '#98971a'
yellow =  '#d79921'
blue =    '#458588'
magenta = '#b16286'
cyan =    '#689d6a'
white =   '#a89984'

[colors.bright]
black =   '#928374'
red =     '#fb4934'
green =   '#b8bb26'
yellow =  '#fabd2f'
blue =    '#83a598'
magenta = '#d3869b'
cyan =    '#8ec07c'
white =   '#ebdbb2'


[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
